// glossary.js — Glossary terms and rendering

// ── Glossary ──────────────────────────────────────────────────────────────────

var GLOSSARY_TERMS = [
  {
    term: 'Accountability',
    pos: 'n.',
    def: 'The obligation to accept responsibility for one\u2019s actions and their consequences \u2014 not selectively, not retroactively, and not only when there is an audience. True accountability is proactive: it does not wait to be caught. It is also structural: it applies regardless of title, tenure, or the number of people one manages or the shares they own. In organisations where accountability is unevenly distributed \u2014 flowing with ease in certain directions, with great resistance in others \u2014 the word tends to appear frequently in company values documents and rarely in practice. This dashboard exists, in part, because accountability does not (as yet).'
  },
  {
    term: 'Apologies',
    pos: 'n. pl.',
    def: 'Expressions of regret for harm caused, intended to acknowledge wrongdoing, restore dignity to the injured party, and signal a genuine intention not to repeat the behaviour. An apology has three components: acknowledgement of what happened, acceptance of responsibility, and a commitment to change. The absence of any one component produces something that resembles an apology but functions as its opposite \u2014 a performative gesture designed to close the conversation rather than address its cause. Apologies are occasionally gestured at, rarely completed, and, in at least one case, apparently scheduled for a future date that has not yet arrived.'
  },
  {
    term: 'AI',
    pos: 'n. (Artificial Intelligence)',
    def: 'A set of computational techniques enabling machines to perform tasks that would otherwise require human intelligence \u2014 such as pattern recognition, language generation, decision support, and, apparently, building dashboards like this. In the context of this project: a tool used to document, organise, and present factual information with a level of precision and consistency that certain human counterparts will find inconvenient. Ironically, AI is here used to debunk AI messianic storytelling aimed to justify raids. AI does not have a career to protect, it simply doesn\u2019t care. This is, depending on your perspective, either its greatest limitations or its most compelling features. The content of this dashboard was not generated by AI. The dashboard itself was. The distinction matters.'
  },
  {
    term: 'Arrogance',
    pos: 'n.',
    def: 'Confidence without invitation. An acute condition affecting individuals who mistake positional authority for intellectual superiority. Often diagnosed post-exit, when the arrogant party discovers the subject they dismissed was, in fact, right. Symptoms include unsolicited Zoom-webinars, stonewalling, treating others as kids, bullying behaviors, and a peculiar allergy to feedback. No known cure; however, exposure to consequences has shown promising early results.'
  },
  {
    term: 'Balls',
    pos: 'n. (also: courage; also: nerve; also: the thing that was required and rarely rewarded)',
    def: 'The capacity to do the right thing when the right thing is hard, costly, or professionally inadvisable. Distinct from recklessness (doing something dangerous without thinking) and from performance (appearing brave without the follow-through). Observed most reliably in individuals who reported misconduct, escalated concerns, or simply told the truth \u2014 and kept telling it, past the point where it would have been convenient negotiating some money.'
  },
  {
    term: 'Boundary',
    pos: 'n.',
    def: 'A limit set by an individual to protect their physical, emotional, or professional wellbeing. Widely recommended by therapists, coaches, and anyone who has ever worked in a dysfunctional organisation. In theory, boundaries are respected. In practice, they are frequently reframed as inflexibility, tested for structural weakness, or simply ignored by people who find them "bureacracy". Setting a boundary requires clarity. Maintaining it requires consistency. Having it acknowledged requires, in many cases, a miracle or cc-ing a legal representative.'
  },
  {
    term: 'Checks and Balances',
    pos: 'n.',
    def: 'A governance mechanism designed to ensure that no single individual or entity accumulates unchecked power. Widely celebrated in theory. Occasionally inconvenient in practice, particularly when the party accumulating unchecked power is also the one responsible for maintaining the checks. See also: irony, hubris, and the entire recorded history of institutional crisis.'
  },
  {
    term: 'Condescendence',
    pos: 'n.',
    def: 'A covert variant of arrogance \u2014 distinguished by its soft tone, its therapeutic vocabulary, and its complete sincerity. The condescending party genuinely believes they are helping. They look at you with the particular warmth of someone who has decided, privately, that you are slightly lost, and they want the best for you. This manifests in several recognisable forms: the unsolicited clarification (\u201cI\u2019m just a little confused about what you\u2019re trying to accomplish\u201d); the counsellor\u2019s formula (\u201chow can we help you?\u201d, deployed as though the responsibility for repairing a year of documented misconduct rests comfortably with the person who experienced it); and the flattering consultation \u2014 asking for your opinion on how to improve the organisation, or who the real rockstars are, as a method of making you feel seen while ensuring nothing changes. Pairs well with mansplaining (the art of explaining things to people who understand them better than you do), unsolicited life advice, and the phrase \u201cMove on and think at your nexr step.\u201d Delivered with the best intentions, always.'
  },
  {
    term: 'Defamation',
    pos: 'n.',
    def: 'The act of making false statements about a person that damage their reputation. Distinguished from criticism (which may be unwelcome but accurate), from feedback (which is supposed to be constructive), and from a performance review (which can be all three at once). In Italian law, <em>diffamazione</em> (595 c.p.) requires that the statement be communicated to at least two people \u2014 a threshold that is, in most professional environments, cleared before the first coffee of the day. The defence of truth remains available, which is why the subject of this dashboard is not particularly worried.'
  },
  {
    term: 'Dignity',
    pos: 'n.',
    def: 'The inherent worth of a person, which exists independently of their title, performance rating, nationality, or the current org chart. Dignity cannot be revoked by a manager, overridden by a policy, or forfeited through resignation. It is, in principle, non-negotiable, non-purchasable, non-sellable. In practice, it is negotiated constantly \u2014 through tone, through process, through the small daily decisions about who gets listened to, who gets believed, and who gets told, with a straight face, that everything is fine. Dignity is the reason why people stay silent, and the reason why they speak up. It is the reason why they leave, and the reason why they stay. It is the reason why they negotiate, and the reason why they refuse to negotiate. It is, in short, everything.'
  },
  {
    term: 'Ego',
    pos: 'n.',
    def: 'The part of the psyche responsible for a person\u2019s sense of self. In healthy quantities, a functional tool. In excess, a full-time organisational hazard. Ego is the leading cause of decisions that prioritise appearances over outcomes, perception over competence, and personal comfort over institutional integrity. It is also, incidentally, the reason why certain people cannot simply say \u201cI was wrong,\u201d preferring instead a nineteen-step process involving reframing, revisionism, and the strategic reassignment of blame. Handle with care. It bruises easily and retaliates disproportionately.'
  },
  {
    term: 'Entrapment',
    pos: 'n.',
    def: 'A manipulative practice designed to fraudulently induce someone into making an error \u2014 and then use that error against them. Purposes vary: sustaining a smear campaign against their reputation, shielding one\u2019s own conduct from its natural consequences, or, in the more ambitious cases, fabricating evidence that any court of law would find inadmissible. When practised within a professional environment, it qualifies as misconduct \u2014 the kind that generates paper trails and glossary entries. When taken to the next level, it becomes something the glossary declines to name directly, but which has its own articles in the Codice Penale.'
  },
  {
    term: 'Gentleness',
    pos: 'n.',
    def: 'Tolerance, patience, a willingness to forgive and to give many chances, and a personal disposition toward self-sacrifice in order to preserve the harmony of the group. Gentleness is not a strategy; it is a character trait \u2014 and like most character traits, it is invisible until it is tested. It is frequently mistaken for weakness, which produces a predictable dynamic: each time the limit is not enforced, it is assumed there is no limit. The boundary is pushed a little further. Then further again. Then once more. And so it continues, quietly and progressively, until the limit is crossed irreversibly \u2014 at which point everything comes back with full force, shocking the other party, who had genuinely grown accustomed to the absence of reaction and was entirely unprepared for an angry or explosive response from someone they had categorised as harmless. The surprise, in these cases, is not a sign that the gentle person changed. It is a sign that they were never actually weak. They were simply patient. There is a difference. It tends to become clear too late.'
  },
  {
    term: 'Gaslighting',
    pos: 'n.',
    def: 'A form of psychological manipulation in which a person is made to question their own perception, memory, or judgement \u2014 typically by someone with more institutional power, more allies in the room, or a stronger interest in the alternative version of events. Techniques include: denying that things were said, reframing documented facts as misunderstandings, suggesting that the subject\u2019s emotional response is the actual problem, and repeating the alternative version of events with such confidence that it begins to feel true. Gaslighting is most effective in environments where the target is isolated, exhausted, or both. It is least effective when the target has been taking notes.'
  },
  {
    term: 'Flying Monkeys',
    pos: 'n. (also: enablers)',
    def: 'Individuals who carry out, amplify, or lend credibility to the actions of a manipulative party \u2014 wittingly or not. Named after the winged enforcers in <em>The Wizard of Oz</em>, who did the witch\u2019s bidding without apparent independent thought. In organisational contexts, flying monkeys may present as loyal colleagues, enthusiastic supporters, or simply people who found it more comfortable to agree than to ask questions. <strong>Enablers</strong> are their quieter variant: they do not act directly, but create the conditions in which harmful behaviour continues unchallenged \u2014 through silence, through validation, or through the deliberate choice to look the other way. Both categories tend to express genuine surprise when the full picture eventually becomes visible. The full picture, of course, was always there.'
  },
  {
    term: 'Ignorance',
    pos: 'n.',
    def: 'The state of not knowing something which is, in principle, a temporary and curable condition resolvable through information, curiosity, or basic professional diligence. In practice, however, it is frequently preferred over knowledge, as the latter tends to impose burdensome obligations, existential doubts, and the nuisance of self-reflection. It typically manifests as a know-it-all complex and a compulsive urge to lecture others, characterized by the delivery of fallacies so profound they are blindingly obvious to anyone with entry-level expertise, yet remain entirely invisible to the speaker who delivers them with adamantine confidence. Voluntary ignorance—the strategic avoidance of any data that would necessitate action—is its more sophisticated cousin and significantly harder to prosecute; it is not to be confused with innocence, which, unlike ignorance, requires a deliberate and taxing kind of work to maintain.'
  },
  {
    term: 'Instability',
    pos: 'n.',
    def: 'A state attributed to individuals who notice, document, or object to things that are actually wrong. Instability is most frequently diagnosed by the party causing the instability, and applied to the subject pointing it out. Clinical literature has not yet confirmed whether the diagnosis reflects a genuine concern for the subject\u2019s wellbeing or a preference for silence. Not to be confused with clarity, accuracy, or a healthy reaction to an abnormal situation. In its purest and likely incurable form, this condition presents as a volatile cocktail of persecutory delusions, control manias, obsessions, and reckless retaliatory actions — and other symptoms typically projected by the aggressor onto the witness. '
  },
  {
    term: 'Integrity',
    pos: 'n.',
    def: 'The quality of being honest and maintaining strong moral principles, consistently and especially when it costs something. Not to be confused with loyalty, compliance, or strategic silence. Individuals with integrity tend to document things, ask inconvenient questions, and leave paper trails. This makes them either very trustworthy or very dangerous, depending entirely on which side of the paper trail you happen to be standing on.'
  },
  {
    term: 'Leadership',
    pos: 'n.',
    def: 'The ability of being consistent and guide, inspire, and take responsibility for a group of people toward a shared goal \u2014 particularly when the goal is difficult, the path is unclear, and the personal cost is real. Not to be confused with management (which is a function), authority (which is a position), or visibility (which is a calendar). True leadership is most easily identified by its absence: when things go wrong and someone put their face on it, and steps forward anyway, that is leadership. When things go wrong and someone steps back, disappears, reframes, delegates, relies on platitudes and lives in denial, that is something else entirely. The literature on leadership is extensive. The practice of it remains niche.'
  },
  {
    term: 'Mafia',
    pos: 'n.',
    def: 'A human, social, and criminal phenomenon originating in Sicily \u2014 forged upon a value system shaped by centuries of external domination and economic underdevelopment, and built around recognisable principles: respect, dignity, the obligation to tell the truth, loyalty to the group. These values, instrumentalised for criminal ends and carried to their logical extreme, become their own perversion: respect becomes fear, loyalty to the group becomes submission to the leader and <em>omert\u00e0</em>, the obligation to tell the truth becomes uncritical conformism.<br><br>It has since been observed, in spirit if not in name, in a remarkable variety of contexts well outside the island.<br><br>Judge Giovanni Falcone \u2014 a real judge, not a self-appointed one \u2014 said: <em>\u201cLa mafia non \u00e8 un cancro proliferato per caso su un tessuto sano. Essa vive in perfetta simbiosi con la miriade di protettori, complici, informatori, debitori di ogni tipo, grandi e piccoli maestri cantori, gente intimidita o ricattata che appartiene a tutti gli strati della societ\u00e0.\u201d</em> (\u201cThe mafia is not a cancer that has proliferated by chance on healthy tissue. It lives in perfect symbiosis with the multitude of protectors, accomplices, informers, debtors of every kind, great and small praise-singers, people intimidated or blackmailed who belong to every stratum of society.\u201d) He also said: <em>\u201cSe vogliamo combattere efficacemente la mafia, dobbiamo riconoscere che ci assomiglia.\u201d</em> (\u201cIf we want to fight the mafia effectively, we must acknowledge that it resembles us.\u201d) \u2014 meaning that it exploits the weaknesses, selfishness, and needs that belong to all of us, poor human beings. If that sounds familiar, the glossary declines to speculate further.<br><br>Today, the phenomenon is primarily economic in nature, having shed most of its cultural charge save what is strictly necessary for territorial control and the recruitment of expendable young men from popular neighbourhoods. An extensive bibliography is available, including in English, for those wishing to go beyond the cinematic representations. Knowledge, as always happens, would allow you to recognise the phenomena and make independent choices, from Liverpool to Las Vegas.<br><br>For the avoidance of doubt: by ruling of 15 March 2018, the EU Tribunal annulled a Spanish trademark using the word <em>Mafia</em>, finding its commercial use contrary to public order and <em>buon costume</em>, on the grounds that it trivialises a dangerous criminal organisation and offends its victims (as, for example, one of the uncles of the Data Subject). A further ruling in 2023 (<em>Mafia Kitchen</em>) made it effectively impossible to register trademarks bearing the word without intervention from the European Court of Justice. Sicilians will explain \u2014 with great patience and only mild irritation \u2014 that the joke stopped being funny some time ago.'
  },
  {
    term: 'Manipulation',
    pos: 'n.',
    def: 'The practice of influencing outcomes through indirect, covert, or deceptive means, rather than through honest communication. Characterised by warmth, plausible deniability, and a recurring cast of intermediaries. Often paired with \u201cno, of course this isn\u2019t personal\u201d and \u201cwe just want what\u2019s best for you.\u201d Not to be confused with leadership, strategy, or people management \u2014 though the confusion, in certain environments, is entirely understandable.'
  },
  {
    term: 'Mirror',
    pos: 'n.',
    def: 'A useful tool that reflects who you are. Best used before talking too much, judging too much, or forming strong opinions about who someone else is. The mirror does not lie, does not selectively recall, and does not reframe what it shows based on the current organisational climate. It simply reflects. What you do with the reflection is, of course, entirely up to you \u2014 which is precisely why many people prefer not to look. Recommended use: at least once a week, ideally in a quiet moment, to verify that the reflection corresponds with your inner conscience. Advanced users may also try it immediately after judging someone else. Results vary. Courage required.'
  },
  {
    term: 'Maturity',
    pos: 'n.',
    def: 'The capacity to regulate one\u2019s emotions, absorb discomfort, and respond to adversity with proportionality rather than escalation. Maturity is not the absence of feeling; it is the presence of judgement. It manifests as the ability to hear difficult truths without retaliating, to be wrong without unravelling, and to prioritise what is right over what is comfortable. In professional environments, it is sometimes confused with passivity, compliance, or simply being quiet. These are not the same thing. Maturity knows the difference. Immaturity, characteristically, does not.'
  },
  {
    term: 'Narcissistic Wound',
    pos: 'n.',
    def: 'The deep psychological injury inflicted upon a narcissist when their self-image is challenged, their authority is questioned, or their audience fails to applaud on cue. Unlike ordinary hurt feelings \u2014 which tend to resolve with time, conversation, or a decent night\u2019s sleep \u2014 the narcissistic wound does not heal quietly. It escalates. It retaliates. It reorganises the entire surrounding environment to ensure the offending party is neutralised, discredited, or simply gone. The wound is, paradoxically, both extremely fragile and extraordinarily dangerous. Handle with caution. Do not, under any circumstances, be right in front of one.'
  },
  {
    term: 'Obsession',
    pos: 'n.',
    def: 'An unwanted, persistent preoccupation with a person, idea, or outcome that overrides rational judgement and proportionate response. In clinical contexts, a symptom. In organisational contexts, occasionally a strategy. Obsession in professional settings tends to masquerade as diligence, thoroughness, or \u201cjust wanting to get to the bottom of things\u201d \u2014 right up until the bottom turns out to be someone else\u2019s personal life, private communications, or whereabouts at 11pm on a Tuesday. At that point, the literature suggests a different diagnosis entirely.'
  },
  {
    term: 'Objectivity',
    pos: 'n.',
    def: 'The rare and coveted capacity to evaluate facts without the distortion of ego, bias, fear, or personal interest. Sometimes invoked by parties who do not possess it, to describe assessments that happen to confirm what they already believed. A spreadsheet can be objective. A person can aspire to it. A dashboard built by the subject of its own content can get surprisingly close \u2014 especially when the facts are this unambiguous.'
  },
  {
    term: 'Privacy',
    pos: 'n.',
    def: 'The right of an individual to control information about themselves. Enshrined in GDPR (EU 2016/679), the Italian Codice Privacy, and the general concept of human dignity. In practice, frequently treated as optional, inconvenient, or inapplicable to people on payroll. For further reading, Articles 12\u201322 of the GDPR remain available and have not been repealed. The Data Subject has read them.'
  },
  {
    term: 'Panopticon',
    pos: 'n.',
    def: 'A prison design conceived by philosopher Jeremy Bentham in the 18th century, in which all inmates can be observed at any time by a single guard positioned at the centre \u2014 without the inmates knowing whether they are being watched at any given moment. The power of the panopticon lies not in constant surveillance, but in the possibility of it: once individuals believe they may be observed, they begin to regulate their own behaviour accordingly. Michel Foucault later used the concept to describe how modern institutions which have nothing to do with prisons \u2014 schools, hospitals, workplaces \u2014 exercise asymmetric power and information, driving the internalisation of control and enabling privacy breaches. The Data Subject is familiar with the concept. Both theoretically and, as it turns out, practically.'
  },
  {
    term: 'Private Vehicles',
    pos: 'n.',
    def: 'Microscopic financial entities \u2014 no employees, no revenue to speak of, located on the other side of the ocean \u2014 through which payments were processed over the course of two years. Their cap table was disclosed proactively and in a timely manner, in the spirit of full transparency, as is the data subject\u2019s documented habit. The suggestion that such an entity could constitute a competitive threat to a company with hundreds of thousands of dollars in turnover and over 350 employees, operating in the United States, is one of two things: ridiculous, or \u2014 on reflection, and with charitable generosity toward the intelligence of all parties involved \u2014 pathological. The glossary declines to choose, and invites the reader to draw their own conclusions.'
  },
  {
    term: 'Stalking',
    pos: 'n.',
    def: 'Persistent, unwanted monitoring of another individual\u2019s movements, communications, or professional activity \u2014 for purposes ranging from \u201coversight\u201d to \u201csecurity\u201d to \u201cI just needed to know.\u201d In professional contexts, sometimes rebranded as performance management, due diligence, or \u201ccultural fit assessment.\u201d The Italian Codice Penale (612-bis c.p.) maintains a more precise and less creative definition.'
  },
  {
    term: 'Substance',
    pos: 'n.',
    def: 'The actual content of a thing, as opposed to its packaging. In professional contexts, substance refers to the quality of ideas, the rigor of analysis, and the depth of contribution \u2014 as distinct from visibility, volume, or the ability to fill a room with confidence. Substance is what remains when the presentation ends, the jargon is removed, and the question \u201cbut what did they actually do?\u201d is asked. It is notably difficult to fake over time, and notably easy to overlook in environments that reward the performance of competence over its exercise. One of the more reliable indicators of substance is that the people who have it tend not to feel the need to announce it. The people who don\u2019t, frequently do.'
  },
  {
    term: 'Uncertainty',
    pos: 'n.',
    def: 'The condition of not knowing what will happen next. Distinct from \u2014 and not to be conflated with \u2014 <strong>ambiguity</strong> (not knowing what something means), <strong>maneuvering</strong> (knowing exactly what you\u2019re doing and ensuring others don\u2019t), <strong>haziness</strong> (not knowing what is currently happening, sometimes deliberately), and <strong>randomness</strong> (the philosophical comfort of attributing intentional patterns to chaos). These five concepts may appear similar in casual conversation. In practice, only one of them is innocent.'
  },
  {
    term: 'Wine',
    pos: 'n.',
    def: 'A fermented beverage produced from grapes, consumed across cultures for thousands of years as a vehicle for celebration, contemplation, and the honest conversation that tends to happen only after the second glass. In the context of this dashboard: a recurring motif, a diplomatic icebreaker, and \u2014 in at least one documented case \u2014 a proposed setting for a non-touristic evening in Milan that would have been excellent and which, regrettably, has not yet occurred. Available overpriced near the Bocconi University. Best enjoyed without the people who always get drunk at the retreat.'
  }
];

function renderGlossary() {
  // Group terms by first letter
  var groups = {};
  GLOSSARY_TERMS.forEach(function(t) {
    var l = t.term.charAt(0).toUpperCase();
    if (!groups[l]) groups[l] = [];
    groups[l].push(t);
  });
  var activeLetters = Object.keys(groups).sort();
  var allLetters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');

  // Alphabet nav bar
  var navBtns = allLetters.map(function(l) {
    if (groups[l]) {
      return '<button onclick="glossScrollTo(\'' + l + '\')"'
        + ' style="flex:1;min-width:0;height:28px;border:none;border-radius:5px;background:transparent;color:var(--accent);font-size:11px;font-weight:600;cursor:pointer;transition:background .12s,color .12s;outline:none"'
        + ' onmouseover="this.style.background=\'var(--accent)\';this.style.color=\'#fff\'"'
        + ' onmouseout="this.style.background=\'transparent\';this.style.color=\'var(--accent)\'">'
        + l + '</button>';
    }
    return '<span style="flex:1;min-width:0;height:28px;display:inline-flex;align-items:center;justify-content:center;font-size:11px;color:var(--border);pointer-events:none">' + l + '</span>';
  }).join('');

  var nav = '<div id="gloss-nav" style="position:sticky;top:0;z-index:10;background:var(--card,#fff);margin-bottom:20px">'
    + '<div style="border:1px solid var(--border);border-radius:8px;background:var(--card,#fff);padding:6px 10px;display:flex;flex-direction:row;align-items:center;box-shadow:0 1px 3px rgba(0,0,0,.06)">'
    + navBtns
    + '</div></div>';

  // Grouped entries — each term in a card
  var content = activeLetters.map(function(l) {
    var cards = groups[l].map(function(t) {
      return '<div style="background:var(--card,#fff);border:1px solid var(--border);border-radius:10px;padding:20px 24px;box-shadow:0 1px 4px rgba(0,0,0,.04)">'
        + '<div style="display:flex;align-items:baseline;gap:10px;margin-bottom:8px">'
        + '<span style="font-size:15px;font-weight:700;color:var(--text)">' + t.term + '</span>'
        + '<span style="font-size:11px;color:var(--muted);font-style:italic">' + t.pos + '</span>'
        + '</div>'
        + '<div style="font-size:13px;color:var(--text);line-height:1.75">' + t.def + '</div>'
        + '</div>';
    }).join('');
    return '<div style="margin-bottom:8px">'
      + '<div id="gloss-' + l + '" style="font-size:11px;font-weight:700;color:var(--accent);letter-spacing:.1em;padding:4px 0 10px">' + l + '</div>'
      + '<div style="display:flex;flex-direction:column;gap:10px">' + cards + '</div>'
      + '</div>';
  }).join('');

  var totalWords = GLOSSARY_TERMS.reduce(function(acc, t) {
    return acc + t.def.replace(/<[^>]+>/g, ' ').trim().split(/\s+/).length;
  }, 0);
  var glossMins = Math.ceil(totalWords / 200);

  return '<div class="ptitle">Glossary</div>'
    + '<div class="psub psub-row" style="margin-bottom:16px">Key terms, precisely defined. Or as precisely as the subject matter allows.' + readTimeBadge(glossMins) + '</div>'
    + '<div style="max-width:960px">'
    + nav
    + content
    + '<div style="padding-top:20px;font-size:11px;color:var(--muted);font-style:italic">More terms will be added as events continue to provide material.</div>'
    + '</div>';
}

function glossScrollTo(l) {
  var el = document.getElementById('gloss-' + l);
  var nav = document.getElementById('gloss-nav');
  var c = document.getElementById('content');
  if (!el || !c) return;
  var navH = nav ? nav.offsetHeight : 44;
  // Convert current screen position to absolute position within the scroll container
  var elAbsTop = el.getBoundingClientRect().top - c.getBoundingClientRect().top + c.scrollTop;
  c.scrollTop = elAbsTop - navH - 8;
}
