// profile.js — Profile page

var PROFILE_SIG_EMAILS = ['bruna@saykudos.co', 'bru.cop10@gmail.com'];

function renderProfile() {
  var userName  = (document.getElementById('un') || {}).textContent || 'Condoadmin';
  var userRole  = (document.getElementById('urole') || {}).textContent || 'Head of Product';

  var frogSvg = '<svg width="64" height="64" viewBox="0 0 36 36" fill="none" class="ld-bob">'
    + '<ellipse cx="18" cy="24" rx="10" ry="7" fill="#9DC47A" opacity=".85"/>'
    + '<ellipse cx="18" cy="22.5" rx="8" ry="5.5" fill="#8BAF6A" opacity=".9"/>'
    + '<circle cx="14" cy="15.5" r="3.2" fill="#6B8A50"/>'
    + '<circle cx="22" cy="15.5" r="3.2" fill="#6B8A50"/>'
    + '<circle cx="14" cy="15.5" r="2" fill="#fff" opacity=".9"/>'
    + '<circle cx="22" cy="15.5" r="2" fill="#fff" opacity=".9"/>'
    + '<circle cx="14.5" cy="15.5" r="1" fill="#2A3A1A"/>'
    + '<circle cx="22.5" cy="15.5" r="1" fill="#2A3A1A"/>'
    + '<path d="M16 22 Q18 24.5 20 22" stroke="#5A7A40" stroke-width="1" fill="none" stroke-linecap="round"/>'
    + '</svg>';

  var nowPlayingCard = ''
    + '<div class="now-playing-card">'
    +   '<div class="now-playing-top">'
    +     '<span class="now-playing-dot"></span>'
    +     '<span class="now-playing-label">Now Playing</span>'
    +   '</div>'
    +   '<div class="now-playing-embed-wrap"><iframe class="now-playing-embed" src="https://open.spotify.com/embed/track/3pc1vNqTREXlPoNYPGAZwU?utm_source=generator" height="80" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe></div>'
    +   '<div class="now-playing-lyrics">'
    +     '<div class="lyrics-row"><span class="lyrics-it">Ci vuol passione</span><span class="lyrics-en">You need passion</span></div>'
    +     '<div class="lyrics-row"><span class="lyrics-it">Molta pazienza</span><span class="lyrics-en">Lots of patience</span></div>'
    +     '<div class="lyrics-row"><span class="lyrics-it">Sciroppo di lampone</span><span class="lyrics-en">Raspberry syrup</span></div>'
    +     '<div class="lyrics-row"><span class="lyrics-it">E un filo di incoscienza</span><span class="lyrics-en">And a hint of recklessness</span></div>'
    +     '<div class="lyrics-break"></div>'
    +     '<div class="lyrics-row"><span class="lyrics-it">Ci vuol farina</span><span class="lyrics-en">You need flour</span></div>'
    +     '<div class="lyrics-row"><span class="lyrics-it">Del proprio sacco</span><span class="lyrics-en">From your own bag</span></div>'
    +     '<div class="lyrics-row"><span class="lyrics-it">Sensualit\u00e0 latina</span><span class="lyrics-en">Latin sensuality</span></div>'
    +     '<div class="lyrics-row"><span class="lyrics-it">E un minimo di stacco</span><span class="lyrics-en">And a touch of detachment</span></div>'
    +     '<div class="lyrics-break"></div>'
    +     '<div class="lyrics-row"><span class="lyrics-it">Si fa cos\u00ec</span><span class="lyrics-en">This is how it\'s done</span></div>'
    +     '<div class="lyrics-row"><span class="lyrics-it">Rossetto e cioccolato</span><span class="lyrics-en">Lipstick and chocolate</span></div>'
    +     '<div class="lyrics-row"><span class="lyrics-it">Che non mangiarli sarebbe un peccato</span><span class="lyrics-en">Not to taste them would be a sin</span></div>'
    +     '<div class="lyrics-row"><span class="lyrics-it">Si fa cos\u00ec</span><span class="lyrics-en">This is how it\'s done</span></div>'
    +     '<div class="lyrics-row"><span class="lyrics-it">Si cuoce a fuoco lento</span><span class="lyrics-en">It simmers on low heat</span></div>'
    +     '<div class="lyrics-row"><span class="lyrics-it">Mescolando con sentimento</span><span class="lyrics-en">Stirring it with feeling</span></div>'
    +     '<div class="lyrics-break"></div>'
    +     '<div class="lyrics-row"><span class="lyrics-it">Le calze nere</span><span class="lyrics-en">Black stockings</span></div>'
    +     '<div class="lyrics-row"><span class="lyrics-it">Il latte bianco</span><span class="lyrics-en">White milk</span></div>'
    +     '<div class="lyrics-row"><span class="lyrics-it">E gi\u00e0 si pu\u00f2 vedere</span><span class="lyrics-en">And you can already see</span></div>'
    +     '<div class="lyrics-row"><span class="lyrics-it">Che piano sta montando</span><span class="lyrics-en">That it\'s slowly rising</span></div>'
    +     '<div class="lyrics-row"><span class="lyrics-it">\u00c8 quasi fatta-ah</span><span class="lyrics-en">It\'s almost done</span></div>'
    +     '<div class="lyrics-row"><span class="lyrics-it">Zucchero a velo</span><span class="lyrics-en">Powdered sugar</span></div>'
    +     '<div class="lyrics-row"><span class="lyrics-it">La gola \u00e8 soddisfatta</span><span class="lyrics-en">The throat is satisfied</span></div>'
    +     '<div class="lyrics-row"><span class="lyrics-it">E nella stanza il cielo</span><span class="lyrics-en">And in the room, the sky</span></div>'
    +     '<div class="lyrics-break"></div>'
    +     '<div class="lyrics-row"><span class="lyrics-it">Si fa cos\u00ec</span><span class="lyrics-en">This is how it\'s done</span></div>'
    +     '<div class="lyrics-row"><span class="lyrics-it">Per cominciare il gioco</span><span class="lyrics-en">To start the game</span></div>'
    +     '<div class="lyrics-row"><span class="lyrics-it">E ci si mastica poco a poco</span><span class="lyrics-en">And you savour it little by little</span></div>'
    +     '<div class="lyrics-row"><span class="lyrics-it">Si fa cos\u00ec</span><span class="lyrics-en">This is how it\'s done</span></div>'
    +     '<div class="lyrics-row"><span class="lyrics-it">\u00c8 tutto apparecchiato</span><span class="lyrics-en">Everything is set</span></div>'
    +     '<div class="lyrics-row"><span class="lyrics-it">Per il cuore e per il palato</span><span class="lyrics-en">For the heart and for the palate</span></div>'
    +     '<div class="lyrics-break"></div>'
    +     '<div class="lyrics-row"><span class="lyrics-it">Sar\u00e0 bello, bellissimo, travolgente</span><span class="lyrics-en">Beautiful, most beautiful, overwhelming</span></div>'
    +     '<div class="lyrics-row"><span class="lyrics-it">Lasciarsi vivere totalmente</span><span class="lyrics-en">To let yourself live completely</span></div>'
    +     '<div class="lyrics-row"><span class="lyrics-it">Dolce, dolcissimo e sconveniente</span><span class="lyrics-en">Sweet, sweetest and indecent</span></div>'
    +     '<div class="lyrics-row"><span class="lyrics-it">Coi bei peccati succede sempre</span><span class="lyrics-en">With beautiful sins it always happens</span></div>'
    +     '<div class="lyrics-break"></div>'
    +     '<div class="lyrics-row"><span class="lyrics-it">Ci vuol fortuna</span><span class="lyrics-en">You need luck</span></div>'
    +     '<div class="lyrics-row"><span class="lyrics-it">Perch\u00e9 funzioni</span><span class="lyrics-en">For it to work</span></div>'
    +     '<div class="lyrics-row"><span class="lyrics-it">I brividi alla schiena</span><span class="lyrics-en">Shivers down the spine</span></div>'
    +     '<div class="lyrics-row"><span class="lyrics-it">E gli ingredienti buoni</span><span class="lyrics-en">And good ingredients</span></div>'
    +     '<div class="lyrics-row"><span class="lyrics-it">\u00c8 quasi fatta-ah</span><span class="lyrics-en">It\'s almost done</span></div>'
    +     '<div class="lyrics-row"><span class="lyrics-it">Zucchero a velo</span><span class="lyrics-en">Powdered sugar</span></div>'
    +     '<div class="lyrics-row"><span class="lyrics-it">La gola \u00e8 soddisfatta</span><span class="lyrics-en">The throat is satisfied</span></div>'
    +     '<div class="lyrics-row"><span class="lyrics-it">E nella stanza il cielo</span><span class="lyrics-en">And in the room, the sky</span></div>'
    +     '<div class="lyrics-break"></div>'
    +     '<div class="lyrics-row"><span class="lyrics-it">Si fa cos\u00ec</span><span class="lyrics-en">This is how it\'s done</span></div>'
    +     '<div class="lyrics-row"><span class="lyrics-it">Per cominciare il gioco</span><span class="lyrics-en">To start the game</span></div>'
    +     '<div class="lyrics-row"><span class="lyrics-it">E ci si mastica poco a poco</span><span class="lyrics-en">And you savour it little by little</span></div>'
    +     '<div class="lyrics-row"><span class="lyrics-it">Si fa cos\u00ec</span><span class="lyrics-en">This is how it\'s done</span></div>'
    +     '<div class="lyrics-row"><span class="lyrics-it">\u00c8 tutto apparecchiato</span><span class="lyrics-en">Everything is set</span></div>'
    +     '<div class="lyrics-row"><span class="lyrics-it">Per il cuore e per il palato</span><span class="lyrics-en">For the heart and for the palate</span></div>'
    +     '<div class="lyrics-break"></div>'
    +     '<div class="lyrics-row"><span class="lyrics-it">Sar\u00e0 bello, bellissimo, travolgente</span><span class="lyrics-en">Beautiful, most beautiful, overwhelming</span></div>'
    +     '<div class="lyrics-row"><span class="lyrics-it">Lasciarsi vivere totalmente</span><span class="lyrics-en">To let yourself live completely</span></div>'
    +     '<div class="lyrics-row"><span class="lyrics-it">Dolce, dolcissimo e sconveniente</span><span class="lyrics-en">Sweet, sweetest and indecent</span></div>'
    +     '<div class="lyrics-row"><span class="lyrics-it">Coi bei peccati succede sempre</span><span class="lyrics-en">With beautiful sins it always happens</span></div>'
    +     '<div class="lyrics-row"><span class="lyrics-it">Coi bei peccati succede sempre</span><span class="lyrics-en">With beautiful sins it always happens</span></div>'
    +   '</div>'
    + '</div>';

  return ''
    + '<div class="prof-layout">'

    +   '<div class="prof-main">'
    +     '<div class="prof-header">'
    +       '<div class="prof-avatar">'+frogSvg+'</div>'
    +       '<div class="prof-identity">'
    +         '<div class="prof-name">'+userName+'</div>'
    +         '<div class="prof-role">'+userRole+'</div>'
    +       '</div>'
    +     '</div>'
    +     '<div class="prof-desc">'
    +       'Manages the shared spaces, enforces the rules nobody agreed to, and keeps the operations running so everyone else can pretend they are delivering results. '
    +       'Responsible for structural decisions, access control, and the kind of coordination work that only becomes visible when it stops happening. 138 IQ-tested: it is a damnation since 1989. '
    +       'Equally socially allergic, either in gritty housing projects and pretentious luxury corporate hotels. Evolved from the good old days of flipping bullies scooters with a rowdy crew, to the sophisticated thrill of crushing them with AI dashboards and regulations.'
    +     '</div>'

    +     '<div class="prof-divider"></div>'

    +     '<div class="prof-section">'
    +       '<div class="prof-section-label">App Stack</div>'
    +       '<div class="prof-desc" style="margin-top:0">Leveraging a high-performing, cross-functional team of one \u2014 similarly to the last 4 years \u2014 this app was ideated, architected, and shipped to production in 2 week-ends \u2014 end-to-end, from prototype to production-grade software \u2014 using Claude Code, Visual Studio Code, Git, Node.js, Vercel, Google Apps Script, EmailJS, and Vercel Blob. No technical debt reduction roadmap was established. Metrics measuring efficiency gains and productivity improvements are, in fact, in the roadmap \u2014 because the author has both the technical depth to build them and the business acumen to know why they matter. Real Genius. Timely change management framework deployment would avoid the need for gargantuan socialization efforts. Now that is built, I have to invent another second job to keep myself from getting bored. Do you have any internal, external, hermaphrodite workflows I could automate like a AI tinkerer pro? </div>'
    +     '</div>'

    +     '<div class="prof-divider"></div>'

    +     '<div class="prof-section">'
    +       '<div class="prof-section-label">Contacts</div>'
    +       '<div class="prof-devtools">'
    +         '<a class="prof-tool-btn" href="mailto:info@getrightshtuffdone.com">'
    +           '<svg width="13" height="13" viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"><rect x="1" y="3" width="14" height="10" rx="1.5"/><path d="M1 4l7 5 7-5"/></svg>'
    +           'Email Developer'
    +         '</a>'
    +       '</div>'
    +     '</div>'
    +   '</div>'

    +   '<div class="prof-sidebar">'+nowPlayingCard+'</div>'

    + '</div>';
}
