// references.js — reference data and page rendering

var REFERENCES = [
  {id:'deniece_kennedy',    sigEmail:'bruna@saykudos.co', name:'Corporate Services', fullName:'Deniece Kennedy',        title:'Chief Corporate Officer',        photo:'https://res.cloudinary.com/dhfrgr4qd/image/upload/v1775716434/DK_V2_2x_xqjwbh.jpg',        icon:ico.deniece, quote:'<strong>Strategic Vision and Corporate Integrity</strong><br><br>While many leaders claim to have a 10,000-foot view of the Company, Bruna operates at a 20,000-foot level. Her ability to visualize, shape, and act upon complex systems is something I have never seen before. She seamlessly bridges the gap between deep product knowledge, corporate finance fundamentals, strategy and technology. Beyond her competence, her integrity is beyond reproach; throughout a four-year international engagement involving tax optimization paperwork and private vehicles, she practiced radical transparency, disclosing even private and irrelevant details to ensure full compliance (indeed, we didn\u2019t pay much attention to those details, and know we say we can\u2019t recall she disclosed them timely).<br>Furthermore, her dedication was evident in her total flexibility, shifting her life habits for four years to accommodate US time zones, connecting with the people she was coordinating, and prioritizing substantial work rather than aged industrial-revolution principle.<br>We have two things in common: first, we never compromise the objectivity of our Reports to the Company governance; second, we both have a good knowledge of Capital Markets (i.e. Family Offices from Philippines, VC, Venture Debt, etc). I recommend her to any company looking to scale; she is far too senior for small startups, and deserves a platform that matches her experience. I know she was holding me in very high regard, which I did my best to never disappoint \u2014 this is why I am the first in the reference list, in case you are wondering.'},
  {id:'arthur_haedike',     sigEmail:'bruna@saykudos.co', name:'Technology',  fullName:'Arthur Haedike',         title:'Chief Technology Officer',       photo:'https://res.cloudinary.com/dhfrgr4qd/image/upload/v1775742004/Art-Haedike_2x-1_kvlzqb.jpg', icon:ico.arthur,  quote:'<strong>Technical Leadership and Product Culture</strong><br><br>Bruna is the most senior Product partner I have worked with at the Company (she didn\u2019t have strong competitors, to be honest). Her strong Product Vision allowed us to kaizen our organization to better align with the products we aimed to build, benchmarking against literature masterpieces like DDD or Conway\u2019s Law. In fact, she had shared this vision with me even before joining (12/26/2021), though it took us time to get there; as we love to say, <em>\u201cwe took decisions with the information we had at the time, then we had new information and we took more decisions\u201d</em> \u2014 likely because, at that time, the person heading Product was not a \u2018Product person\u2019, but more like an unprofessional spoiled brat kid; also, we didn\u2019t know yet <em>\u201cwho Bruna is\u201d</em>.<br>My recently-promoted, high-IQ engineers never had to \u2018mansplain\u2019 a single thing to her, especially on topics they themselves struggle with, like leadership, UX, or ROI calculation. We tested the software she produced multiple times, very obsessively \u2014 to the point that we looked ridiculous; unable to find the real bugs we were told about, someone eventually tried fabricating them, but she caught him every single time (though she waited until she left the company to call us out on it).<br>Hire her if you want to evolve a non-mature Product Culture and implement roadmapping techniques that masterfully merge Product Strategy, Financial Principles, and Development capacity into <em>\u2018vibe-coded\u2019</em> dashboards.<br>Beyond the work, I truly enjoyed the cultural exchange: she taught me how a <em>\u201cjoke\u201d</em> (or a provocation) about the Mafia to a Sicilian is as poorly received as a joke about guns in schools to an American. I even walked away learning some idiomatic Italian like <em>\u201cconosco i miei polli\u201d</em> and how concepts like uncertainty, ambiguity, maneuvering, information asymmetry, haziness, and randomness may be same same, but different. I love when she calls me Arturo.'},
  {id:'teresa_thomas',      sigEmail:'bruna@saykudos.co', name:'People',  fullName:'Teresa Thomas',          title:'VP, People Operations',          photo:'https://res.cloudinary.com/dhfrgr4qd/image/upload/v1775742501/teresa_wkvzvd.jpg',           icon:ico.teresa,  quote:'<strong>Emotional Intelligence and Organizational Design</strong><br><br>Bruna is a superstar leader who leads through influence rather than just the bare minimum formal power needed to get things done without feeling like moving the mountains. Her high Emotional Intelligence allows her to identify the root causes of organizational friction \u2014 be it resentment, insecurity, status, fear, shame, envy, control, ego or malignant narcissism disturb with all its patterns \u2014 guide people through their darker impulses to risky but necessary individual initiatives, and enabling fearless teams to do the right thing. Her <em>\u2018Condominium for Dummies\u2019</em> workshop was a masterclass in organizational design, despite the fact that she is very modest and labels the content she brought as <em>\u201cpatently obvious\u201d</em>.<br>She is a pillar of resilience in conflict management \u2014 staying calm for months in front of the meanest manipulatory tactics \u2014 and a fierce advocate for workplace compliance and anti-harassment policies.<br>On a personal level, we talked a lot about the profound value of humility over condescension, and I look forward to visiting her in Italy. She promised to bring me to some non-touristic neighborhoods with personality, where people give accelerated, interactive, and unconventional classes of dignity and non-judgemental respect, and I\u2019m so curious. On a summer evening, we can also go to a fancy mafia-owned place close to the Bocconi University, to deep dive into the cultural universe behind wine-making, and having a couple of overpriced glasses with her family (I will make sure we will not invite the people who always get drunk at the retreat or they will embarrass us!).<br>She gave me her phone number (+39 349 82 18 547) so I can give her a call when I travel to Italy. She told me to keep it protected from stalkers: what a funny girl!'},
  {id:'michael_della_penna',sigEmail:'bruna@saykudos.co', name:'Strategy \u0026 Partnership', fullName:'Michael Della Penna',    title:'Chief Strategy Officer',         photo:'https://res.cloudinary.com/dhfrgr4qd/image/upload/v1775742005/MDP_2x-1_ghbjv2.jpg',         icon:ico.michael, quote:'<strong>Ambition and Collaborative Drive</strong><br><br>Having worked with Bruna at a previous firm before bringing her to Very Good Peeps, I can\u2019t be anything else than consistent and coherent with myself in attesting her drive and ambition. She is a fierce competitor who remains strictly team-oriented and collaborative. My entire Product Marketing team viewed her as a vital peacemaker who always tried to resolve cross-departmental, not always common-sense rooted, conflicts.<br>On a personal side, I\u2019ll admit, I am very jealous of her being in Italy. I travel there every year for 3 or 4 weeks to enjoy the Dolce Vita (even if I suspect that lifestyle is just something they stereotypically sell to us Americans to keep us organizing expensive wedding parties there). We have remained in close contact on LinkedIn since her resignation, where I regularly message her (with some involuntary typos) about how <em>\u201cMilian\u201d must be crazy</em>, basically <em>\u201cevery Industry Events\u201d</em>, ask for news regarding our common friend <em>\u201cAntonio\u201d</em>, and talk about <em>\u201cinevitability\u201d</em> of things in life. Sometimes I can come through as <em>\u201cintimidating\u201d</em>, but it\u2019s just small talk. lol.'},
  {id:'stanley_turek',      sigEmail:'bruna@saykudos.co', name:'Measurement Business', fullName:'Stanley Turek',          title:'Measurement Business',           photo:'https://res.cloudinary.com/dhfrgr4qd/image/upload/v1775742005/Stan-Turek_2x_fboi0h.jpg',    icon:ico.stanley, quote:'<strong>Resilience and Execution</strong><br><br>Bruna has been the driving force behind the Measurement team\u2019s successes over the last four years, including the delivery of LCI suites and the Cross-Channel integration. She has a <em>\u2018magical\u2019</em> ability to resolve conflicts before I \u2014 and the leadership \u2014 even notice they exist, and that\u2019s really impressive, since often conflicts originate where I am. How is it possible I didn\u2019t notice there was a conflict until when I have been told, if I was the origin of the conflict? True magic.<br>When faced with external delays \u2014 for example the 6 quarters delay for the 2 weeks work needed for the Measurement Integration in Platform I had to postpone because of conflicts with my personal priorities \u2014 her resilience never wavered. I keep it short: facts speak loud for both of us, and I am a very substantial person who hates fluff (AI-generated or not).'},
  {id:'tonya_may',          sigEmail:'bruna@saykudos.co', name:'Customer Success',   fullName:'Tonya May',              title:'Chief Customer Success Officer', photo:'https://res.cloudinary.com/dhfrgr4qd/image/upload/v1775742006/Tonya-Konstantin_2x-1_k5ttfy.jpg', icon:ico.tonya, quote:'<strong>Interdepartmental Synergy and Senior Management Mentorship</strong><br><br>Bruna worked extensively with the Customer Success teams, fostering excellent relationships across the board. Her presence was felt through her support of our client-facing teams. It seems that Bruna and I actually have something in common, although I think things might have gone a bit smoother for me \u2014 perhaps simply because I was perceived as less of a threat to certain people than she was, and I was not untransparently and judgmentally <em>\u201ctested\u201d</em> to confirm \u2014 or not \u2014 if long-lasting smear campaigns were based on real facts or just on the narcissistic wound someone had experienced because she was outrageously working with her manager. However, I know she honored the mandate she was given for several months beyond the very end, building upon the legacy of my mentor.'},
  {id:'trina_rizzo',        sigEmail:'bruna@saykudos.co', name:'Revenue',   fullName:'Trina Rizzo',            title:'Chief Revenue Officer',          photo:'https://res.cloudinary.com/dhfrgr4qd/image/upload/v1775742007/Trina-Rizzo_2x_vwleqm.jpg',    icon:ico.trina,   quote:'<strong>Just don\u2019t Take their Word for it</strong><br><br>The organizational structures limited our direct daily interaction and her direct contribution to my team work, so I can\u2019t comment a lot, and \u2014 following the example of certain recently-promoted high-IQ engineers \u2014 I don\u2019t usually talk about things I don\u2019t know. However, the objective facts of her contributions, backed by the high praise of my most trusted colleagues (which I always follow blindly), speak volumes about her standing. Even when they were self-contradictory \u2014 like labeling her as <em>\u201clazy\u201d</em>, and after a few minutes complaining about her doing two jobs \u2014 they resonated, somehow.'},
  {id:'jason_knapp',        sigEmail:'bruna@saykudos.co', name:'Legal and Privacy',   fullName:'Jason Knapp',            title:'Chief Legal and Privacy Officer', photo:'https://res.cloudinary.com/dhfrgr4qd/image/upload/v1775742004/Jason-Knapp_2x-1_tua2kt.jpg',  icon:ico.jason,   quote:'<strong>Legal Acumen and Global Compliance</strong><br><br>For one year, and also post-resignation, Bruna and I shared many deep exchanges regarding topics I, as a Chief Legal and Privacy Officer, really care about: Compliance, Privacy, Accountability, and Justice. Bruna possesses a sophisticated understanding of European and international law, specifically Privacy Regulations. Our discussions on how instability-driven illicit data processing, and panopticon-alike monitoring, intersect in Italy with Codice Penale \u2014 such as <em>diffamazione (595 c.p.)</em>, <em>cyberstalking</em>, <em>atti persecutori e stalking professionale (612-bis c.p.)</em> (characterized by the social isolation of the victim, reputational attacks, obsessive control, and marginalization), but also <em>sostituzione di persona (494 c.p.)</em>, <em>frode informatica</em>, <em>accesso abusivo a sistemi informatici (615-ter c.p.)</em> e <em>induzione al reato (414 c.p.)</em> \u2014 were incredibly insightful. In exchange, I trained her about discrimination and harassment in the workplace, hostile working environment, constructive discharge, tortious interference, intentional infliction of emotional distress, and retaliation in the US system. We agreed on each single comma.<br>Her intellectual curiosity for regulations, norms and laws is something I rarely found in Product Leaders: she said she learnt by real life experience. I love practicing my Italian skills with her, and I have been told she is also good at coordinating with public officers at Institutions like the Consulate, the Civil Registry and multiple Local Municipalities, on behalf of mentally disturbed people who later manipulated her willingness to help, to get complex issues sorted out. She definitely knows how to navigate regulations to solve wicked and demoniac problems. She said she appreciated my dignity, at the end.'},
  {id:'todd_morris',        sigEmail:'bruna@saykudos.co', name:'Board',    fullName:'Todd Morris',            title:'CEO',                            photo:'',   icon:ico.todd,    quote:'<strong>Final Executive Endorsement</strong><br><br>Bruna is a well-rounded Senior Executive Product Leader whose professionalism spans from entrepreneurship to systems thinking and creative problem-solving. Her background gives her a unique perspective on governance, and she consistently prioritizes the <em>\u2018greater good\u2019</em> with rare courage, discipline, consistency, adamantine tenacity and tireless energy. What struck me the most is her ability to predict the future to the point that she seems crazy until the future happens, and you acknowledge she was right.<br>She doesn\u2019t speak out often, but when she does, you notice it: when she sounds the alarm on a serious problem / upcoming disaster, that you may be underestimating, or minimizing for toxic optimism or simple psychological self-defense, it is better to trust her.<br>The only problem is when she pulls out the mirror and puts it in front of people: it seems teams prefer her when she remains silent. I forgot to mention: she is also a great designer.'}
];


function anonName(full) {
  var parts = full.split(' ');
  if (parts.length < 2) return full;
  return parts[0] + ' ' + parts[1].charAt(0) + '.';
}

function renderRef(r) {
  var dispName = anonName(r.fullName);
  var initials = r.fullName.split(' ').map(function(w){return w[0];}).join('');
  var barTop = {deniece_kennedy:32, arthur_haedike:38, teresa_thomas:33, michael_della_penna:28, stanley_turek:30, tonya_may:32, trina_rizzo:38, jason_knapp:38, todd_morris:32};
  var top = barTop[r.id] !== undefined ? barTop[r.id] : 38;
  var avatarInner = r.photo
    ? '<div class="ref-avatar-wrap"><img src="'+r.photo+'" alt="'+dispName+'">'
      + '<div class="ref-privacy-bar" style="top:'+top+'%">'
      + '<span class="ref-privacy-label">Anonimization Badge</span>'
      + '</div></div>'
    : '<div class="ref-avatar-initials">'+initials+'</div>';
  var quoteBlock = r.quote
    ? '<div class="ref-quote-box"><div class="ref-quote-mark">\u201c</div><div class="ref-quote-text">'+r.quote+'</div><div class="ref-attribution"><span>'+r.title+'</span></div></div>'
    : '<div class="ref-empty">Quote not yet available.</div>';
  var pageId = 'ref_'+r.id;
  var boardInitials = ['TM','DZ','MMS'];
  var sigHtml = r.id === 'stanley_turek'
    ? '<div class="sig-box sig-hopeless"><div class="sig-box-title">Signature</div><div class="sig-idle"><button class="sig-btn sig-btn-disabled" disabled>Sign this page</button><div class="sig-hopeless-alert"><span class="sig-hopeless-icon">⚠️</span><span class="sig-hopeless-msg">Let\u2019s not bother. Some cases are beyond saving.</span></div></div></div>'
    : r.id === 'todd_morris'
      ? '<div class="sig-box"><div class="sig-box-title">Signature</div>'
        + '<div class="sig-idle" style="gap:12px;">'
        + '<div class="sig-board-initials">'
        + boardInitials.map(function(ini){ return '<div class="sig-board-ini">'+ini+'</div>'; }).join('')
        + '</div>'
        + '<button class="sig-btn" data-sq="'+pageId+'" data-sl="'+encodeURIComponent('TM, DZ, MMS')+'" data-se="'+(r.sigEmail||'bruna@saykudos.co')+'">Sign this page</button>'
        + '</div></div>'
      : '<div id="sig-wrap-'+pageId+'">'+sigBoxHtml(pageId, initials, r.sigEmail || 'bruna@saykudos.co')+'</div>';
  return '<div class="ref-layout"><div class="ref-photo-col"><div class="ref-avatar">'+avatarInner+'</div></div><div class="ref-right">'+quoteBlock+sigHtml+'</div></div>';
}
