// roadmap.js — navigation config, data helpers, roadmap rendering


var NAV_CONFIG = [
  {section:'Product', items:[
    {id:'roadmap',      label:'Product Roadmap',   icon:ico.roadmap},
    {id:'teamcapacity', label:'Team Capacity',      icon:'<svg width="16" height="16" viewBox="0 0 16 16" fill="none"><circle cx="5" cy="6" r="2.5" stroke="currentColor" stroke-width="1.4" opacity=".7"/><circle cx="11" cy="6" r="2.5" stroke="currentColor" stroke-width="1.4" opacity=".4"/><path d="M1 14c0-2.2 1.8-4 4-4s4 1.8 4 4" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" opacity=".7"/><path d="M11 10c1.7.4 3 1.9 3 3.7" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" opacity=".4"/></svg>'}
  ]},
  {section:'References from Very Good Peeps', items:REFERENCES.map(function(r){return{id:'ref_'+r.id,label:r.name,icon:r.icon};}).concat([{id:'wip',label:'Work in Progress',icon:ico.wip}])},
  {section:'Resources', items:[{id:'resources',label:'Recognize the Patterns',icon:ico.resources},{id:'boilingfrog',label:'The Boiling Frog',icon:ico.frog}]}
];

var initiatives=[],deliveryOpts=[
  {val:'not-started',label:'Not Started',cls:'ds-gray'},
  {val:'on-track',   label:'On Track',   cls:'ds-green'},
  {val:'at-risk',    label:'At Risk',    cls:'ds-yellow'},
  {val:'delayed',    label:'Delayed',    cls:'ds-red'}
];
var activeId='roadmap',collapsed=false,_linkIdx=null;

function currentQ(){var m=new Date().getMonth();return 'Q'+(m<3?1:m<6?2:m<9?3:4);}
function currentQLabel(){var m=new Date().getMonth(),y=new Date().getFullYear();return 'Q'+(m<3?1:m<6?2:m<9?3:4)+' '+y;}
function fmtDollar(v){if(!v||v==='\u2014')return '\u2014';var n=parseFloat(String(v).replace(/[^0-9.-]/g,''));if(isNaN(n))return String(v);return '$'+n.toFixed(2).replace(/\B(?=(\d{3})+(?!\d))/g,',');}
function roiHtml(v){if(!v||v==='\u2014')return '\u2014';var n=parseFloat(String(v).replace(/[^0-9.-]/g,''));if(isNaN(n))return String(v);var p=Math.round(n*100);return '<span class="roi-pct '+(p<0?'roi-pct-neg':'roi-pct-pos')+'">'+p+'%</span>';}
function dsHtml(idx){var cur=initiatives[idx].deliveryStatus,opt=deliveryOpts.filter(function(o){return o.val===cur;})[0]||deliveryOpts[0];return '<div class="ds-wrap" data-idx="'+idx+'"><span class="pill ds-pill '+opt.cls+'" id="ds-pill-'+idx+'">'+opt.label+'</span></div>';}
function linkIconHtml(idx){var i=initiatives[idx],cls='link-btn'+(i.link?' has-link':'');return '<button class="'+cls+'" data-link-idx="'+idx+'" title="'+(i.link?'Edit link':'Add link')+'"><svg width="12" height="12" viewBox="0 0 16 16" fill="none"><path d="M6.5 9.5a4 4 0 005.66 0l2-2a4 4 0 00-5.66-5.66L7.44 2.94" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/><path d="M9.5 6.5a4 4 0 00-5.66 0l-2 2a4 4 0 005.66 5.66l1.06-1.06" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/></svg></button>';}
function titleCellHtml(idx){var i=initiatives[idx],t=i.link?'<a href="'+i.link+'" target="_blank" class="init-title">'+i.title+'</a>':'<span class="init-title">'+i.title+'</span>';return '<div class="init-cell">'+t+linkIconHtml(idx)+'</div>';}
function saveLocalState(){var s={};initiatives.forEach(function(i,idx){s[idx]={deliveryStatus:i.deliveryStatus,link:i.link};});try{localStorage.setItem('inmarket_state',JSON.stringify(s));}catch(e){}}
function loadLocalState(cb){try{var r=localStorage.getItem('inmarket_state');if(r){var ls=JSON.parse(r);Object.keys(ls).forEach(function(idx){var i=initiatives[parseInt(idx)];if(!i)return;i.deliveryStatus=ls[idx].deliveryStatus||i.deliveryStatus;i.link=ls[idx].link||i.link;});}}catch(e){}if(cb)cb();}
function roiCalcGroup(items){var a=0,rs=0,rc=0;items.forEach(function(i){var av=parseFloat(String(i.addedValue||'').replace(/[^0-9.-]/g,''));if(!isNaN(av))a+=av;var r=parseFloat(String(i.roi||'').replace(/[^0-9.-]/g,''));if(!isNaN(r)){rs+=r;rc++;}});return{count:items.length,av:a,roiAvg:rc?rs/rc:NaN};}
function roiFmtAV(n){if(!n&&n!==0)return '\u2014';if(n>=1000000)return '$'+(n/1000000).toFixed(2)+'M';if(n>=1000)return '$'+(n/1000).toFixed(2)+'K';return '$'+n.toFixed(2);}
function roiFmtEU(n){if(!n&&n!==0)return '\u2014';return '$'+n.toFixed(2).replace('.',',').replace(/\B(?=(\d{3})+(?!\d))/g,'.');}
function buildQFilter(prefix,fn){var cq=currentQ();return '<div class="qfilter">'+['Q1','Q2','Q3','Q4','all'].map(function(q){var lbl=q==='all'?'All Year':q,act=q===cq;return '<button id="'+prefix+'-btn-'+q+'" class="qfilter-btn'+(act?' act':'')+'" data-qfn="'+fn+'" data-q="'+q+'">'+lbl+'</button>';}).join('')+'</div>';}
function setQAct(prefix,q){['Q1','Q2','Q3','Q4','all'].forEach(function(b){var el=document.getElementById(prefix+'-btn-'+b);if(el){if(b===q)el.classList.add('act');else el.classList.remove('act');}});}
function scInitiativesFor(subset,label){var ns=subset.filter(function(i){return i.deliveryStatus==='not-started';}).length,on=subset.filter(function(i){return i.deliveryStatus==='on-track';}).length,ar=subset.filter(function(i){return i.deliveryStatus==='at-risk';}).length,dl=subset.filter(function(i){return i.deliveryStatus==='delayed';}).length;return '<div class="mcard" id="sc-init"><div class="mlabel">Initiatives <span class="sc-qlabel">'+label+'</span></div><div class="mval">'+subset.length+'</div><div class="sc-badges"><span class="sc-badge ds-gray">'+ns+' Not Started</span><span class="sc-badge ds-green">'+on+' On Track</span><span class="sc-badge ds-yellow">'+ar+' At Risk</span><span class="sc-badge ds-red">'+dl+' Delayed</span></div></div>';}
function scGroupedFor(id,label,key,subset,qlabel){var groups={};subset.forEach(function(i){var k=i[key];if(!groups[k])groups[k]={'not-started':0,'on-track':0,'at-risk':0,'delayed':0};groups[k][i.deliveryStatus]++;});var rows=Object.keys(groups).map(function(k){var g=groups[k],pills='';if(g['not-started']>0)pills+='<span class="sc-group-pill ds-gray">'+g['not-started']+'</span>';if(g['on-track']>0)pills+='<span class="sc-group-pill ds-green">'+g['on-track']+'</span>';if(g['at-risk']>0)pills+='<span class="sc-group-pill ds-yellow">'+g['at-risk']+'</span>';if(g['delayed']>0)pills+='<span class="sc-group-pill ds-red">'+g['delayed']+'</span>';return '<div class="sc-group-row"><span class="sc-group-name">'+k+'</span><div class="sc-group-pills">'+pills+'</div></div>';}).join('');return '<div class="mcard" id="'+id+'"><div class="mlabel">'+label+' <span class="sc-qlabel">'+qlabel+'</span></div><div class="sc-group-body">'+rows+'</div></div>';}
function refreshCards(subset,label){var sc=document.getElementById('sc-init');if(sc)sc.outerHTML=scInitiativesFor(subset,label);['sc-driver','sc-theme','sc-team'].forEach(function(id,i){var keys=['driver','theme','team'],el=document.getElementById(id);if(el)el.outerHTML=scGroupedFor(id,['By Driver','By Theme','By Team'][i],keys[i],subset,label);});}
function scInitiatives(){var cq=currentQ(),inQ=initiatives.filter(function(i){return i.quarter===cq;});return scInitiativesFor(inQ,currentQLabel());}
function scGrouped(id,label,key){var cq=currentQ(),inQ=initiatives.filter(function(i){return i.quarter===cq;});return scGroupedFor(id,label,key,inQ,currentQLabel());}
function buildFilterOptions(key){var v=[];initiatives.forEach(function(i){if(v.indexOf(i[key])===-1)v.push(i[key]);});v.sort();return v.map(function(x){return '<option value="'+x+'">'+x+'</option>';}).join('');}
function buildFilterBar(s){s=s||'';var ds=deliveryOpts.map(function(o){return '<option value="'+o.val+'">'+o.label+'</option>';}).join('');return '<div class="filterbar"><select id="f-driver'+s+'" data-filter="'+s+'"><option value="">All Drivers</option>'+buildFilterOptions('driver')+'</select><select id="f-team'+s+'" data-filter="'+s+'"><option value="">All Teams</option>'+buildFilterOptions('team')+'</select><select id="f-theme'+s+'" data-filter="'+s+'"><option value="">All Themes</option>'+buildFilterOptions('theme')+'</select><select id="f-po'+s+'" data-filter="'+s+'"><option value="">All Product Owners</option>'+buildFilterOptions('productOwner')+'</select><select id="f-tl'+s+'" data-filter="'+s+'"><option value="">All Tech Leads</option>'+buildFilterOptions('techLead')+'</select><select id="f-status'+s+'" data-filter="'+s+'"><option value="">All Statuses</option>'+ds+'</select><button class="filter-reset" data-reset="'+s+'">Reset</button></div>';}
function applyFilters(){var fd=document.getElementById('f-driver'),ft=document.getElementById('f-team'),fth=document.getElementById('f-theme'),fpo=document.getElementById('f-po'),ftl=document.getElementById('f-tl'),fs=document.getElementById('f-status');document.querySelectorAll('#rt-table table tbody tr').forEach(function(row,idx){var i=initiatives[idx];if(!i){row.style.display='none';return;}row.style.display=(!fd||!fd.value||i.driver===fd.value)&&(!ft||!ft.value||i.team===ft.value)&&(!fth||!fth.value||i.theme===fth.value)&&(!fpo||!fpo.value||i.productOwner===fpo.value)&&(!ftl||!ftl.value||i.techLead===ftl.value)&&(!fs||!fs.value||i.deliveryStatus===fs.value)?'':'none';});}
function resetFilters(){['f-driver','f-team','f-theme','f-po','f-tl','f-status'].forEach(function(id){var el=document.getElementById(id);if(el)el.value='';});document.querySelectorAll('#rt-table table tbody tr').forEach(function(r){r.style.display='';});}
function switchTableQuarter(q){var label=q==='all'?'All Year':q,subset=q==='all'?initiatives:initiatives.filter(function(i){return i.quarter===q;});var rows=subset.map(function(i){var idx=initiatives.indexOf(i);return '<tr><td>'+i.quarter+'</td><td>'+titleCellHtml(idx)+'</td><td>'+i.driver+'</td><td>'+i.productOwner+'</td><td>'+i.techLead+'</td><td>'+i.theme+'</td><td>'+i.team+'</td><td>'+fmtDollar(i.addedValue)+'</td><td>'+roiHtml(i.roi)+'</td><td>'+dsHtml(idx)+'</td></tr>';}).join('');var tbody=document.querySelector('#rt-table table tbody');if(tbody)tbody.innerHTML=rows;refreshCards(subset,label);setQAct('tbl',q);}
function switchKanbanQuarter(q){var quarters=['Q1','Q2','Q3','Q4','Backlog'];document.querySelectorAll('#kanban-wrap .kancol').forEach(function(col,i){col.style.display=(q==='all'||quarters[i]===q)?'':'none';});setQAct('kan',q);}
function switchROIQuarter(q){document.getElementById('roi-content').innerHTML=buildScatterPlot(q)+roiRenderContent(q);setTimeout(function(){renderScatterChart(q);},50);setQAct('roi',q);}
function buildQuarterlyProgressBars(){var quarters=['Q1','Q2','Q3','Q4','Backlog'];return '<div class="qprog-grid">'+quarters.map(function(q){var items=initiatives.filter(function(i){return i.quarter===q;}),total=items.length||1;var ns=items.filter(function(i){return i.deliveryStatus==='not-started';}).length,on=items.filter(function(i){return i.deliveryStatus==='on-track';}).length,ar=items.filter(function(i){return i.deliveryStatus==='at-risk';}).length,dl=items.filter(function(i){return i.deliveryStatus==='delayed';}).length;var avSum=0;items.forEach(function(i){var n=parseFloat(String(i.addedValue||'').replace(/[^0-9.-]/g,''));if(!isNaN(n))avSum+=n;});var avLbl=avSum>=1000000?'$'+(avSum/1000000).toFixed(1)+'M':avSum>=1000?'$'+(avSum/1000).toFixed(0)+'K':avSum>0?'$'+avSum.toFixed(0):'\u2014';var nsW=Math.round(ns/total*100),onW=Math.round(on/total*100),arW=Math.round(ar/total*100),dlW=Math.round(dl/total*100);var meta=(ns>0?ns+' not started \u00b7 ':'')+(on>0?on+' on track \u00b7 ':'')+(ar>0?ar+' at risk \u00b7 ':'')+(dl>0?dl+' delayed':'');if(items.length===0)meta='No initiatives';var roiSum=0,roiCount=0;items.forEach(function(i){var r=parseFloat(String(i.roi||'').replace(/[^0-9.-]/g,''));if(!isNaN(r)){roiSum+=r;roiCount++;}});var roiPct=roiCount?Math.round(roiSum/roiCount*100)+'%':'\u2014';return '<div class="qprog-card"><div class="qprog-head"><span class="qprog-q">'+q+'</span><span class="qprog-count">'+items.length+'</span></div><div class="qprog-body"><div class="qprog-bar">'+(nsW>0?'<div class="qprog-seg-ns" style="flex:'+nsW+'"></div>':'')+(onW>0?'<div class="qprog-seg-on" style="flex:'+onW+'"></div>':'')+(arW>0?'<div class="qprog-seg-ar" style="flex:'+arW+'"></div>':'')+(dlW>0?'<div class="qprog-seg-dl" style="flex:'+dlW+'"></div>':'')+(items.length===0?'<div class="qprog-seg-empty" style="flex:1"></div>':'')+'</div><div class="qprog-meta">'+meta+'</div></div><div class="qprog-foot"><div class="qprog-foot-label">Avg ROI</div><div class="qprog-foot-val">'+roiPct+' <span class="qprog-foot-sub">('+avLbl+')</span></div></div></div>';}).join('')+'</div>';}
function buildScatterPlot(q){var subset=q==='all'?initiatives.filter(function(i){return i.quarter!=='Backlog';}):initiatives.filter(function(i){return i.quarter===q;});var driverColors={'Revenue Generating':'#66C220','Operational Efficiency':'#854F0B','Enhancements':'#888780','Strategic':'#185FA5','Tech':'#0D1E36'};var drivers=[];subset.forEach(function(i){if(drivers.indexOf(i.driver)===-1)drivers.push(i.driver);});drivers.sort();return '<div class="scatter-wrap"><div class="scatter-title">Added Value vs ROI \u2014 each point is an initiative</div><div class="scatter-canvas"><canvas id="roiScatterCanvas"></canvas></div><div class="scatter-legend">'+drivers.map(function(d){var c=driverColors[d]||'#888780';return '<span class="scatter-legend-item"><span class="scatter-legend-dot" style="background:'+c+'"></span>'+d+'</span>';}).join('')+'</div></div>';}
function renderScatterChart(q){var subset=q==='all'?initiatives.filter(function(i){return i.quarter!=='Backlog';}):initiatives.filter(function(i){return i.quarter===q;});var driverColors={'Revenue Generating':'#66C220','Operational Efficiency':'#854F0B','Enhancements':'#888780','Strategic':'#185FA5','Tech':'#0D1E36'};var drivers=[];subset.forEach(function(i){if(drivers.indexOf(i.driver)===-1)drivers.push(i.driver);});drivers.sort();var datasets=drivers.map(function(d){var color=driverColors[d]||'#888780';var pts=subset.filter(function(i){return i.driver===d;}).map(function(i){var av=parseFloat(String(i.addedValue||'').replace(/[^0-9.-]/g,'')),roi=parseFloat(String(i.roi||'').replace(/[^0-9.-]/g,''));if(isNaN(av)||isNaN(roi))return null;return{x:av,y:Math.round(roi*100),label:i.title};}).filter(Boolean);return{label:d,data:pts,backgroundColor:color+'99',borderColor:color,pointRadius:7,pointHoverRadius:10};});var canvas=document.getElementById('roiScatterCanvas');if(!canvas||!window.Chart)return;if(window._roiChart)window._roiChart.destroy();window._roiChart=new Chart(canvas,{type:'scatter',data:{datasets:datasets},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:function(c){return c.raw.label+' \u2014 $'+c.raw.x+'K, '+c.raw.y+'%';}}}},scales:{x:{title:{display:true,text:'Added Value ($K)',font:{size:11}},ticks:{font:{size:11},callback:function(v){return '$'+v+'K';}}},y:{title:{display:true,text:'ROI %',font:{size:11}},ticks:{font:{size:11},callback:function(v){return v+'%';}}}},layout:{padding:10}}});}
function roiMakeOverallCard(subset,label){var s=roiCalcGroup(subset),p=isNaN(s.roiAvg)?0:Math.round(s.roiAvg*100),c=p<0?'#E24B4A':'#66C220';return '<div class="roi-card roi-card-overall"><div class="roi-card-title">Overall ROI &mdash; '+label+'</div><div><div class="roi-big-val">'+s.count+'</div><div class="roi-sub">initiatives</div></div><div class="roi-divider"></div><div><div class="roi-med-val">'+roiFmtAV(s.av)+'</div><div class="roi-sub">added value</div></div><div class="roi-divider"></div><div><div class="roi-med-val" style="color:'+c+'">'+p+'%</div><div class="roi-sub">avg ROI</div></div></div>';}
function roiMakeBarCard(subset,title,label,key){var keys=[];subset.forEach(function(i){if(keys.indexOf(i[key])===-1)keys.push(i[key]);});keys.sort();var rows=keys.map(function(k,ki){var s=roiCalcGroup(subset.filter(function(i){return i[key]===k;})),p=isNaN(s.roiAvg)?0:Math.round(s.roiAvg*100),tc=p<0?'#E24B4A':'#3B6D11';return '<div class="roi-bar-row"><div class="roi-bar-name">'+k+'</div><div class="roi-bar-av">'+roiFmtEU(s.av)+'</div><div class="roi-bar-pct" style="color:'+tc+'">'+p+'%</div></div>';}).join('');var hdr='<div class="roi-bar-hdr"><div></div><div class="roi-bar-hdr-av">Added Value</div><div class="roi-bar-hdr-cell">Avg ROI</div></div>';return '<div class="roi-card"><div class="roi-card-title-mb">'+title+' &mdash; '+label+'</div>'+hdr+rows+'</div>';}
function roiMakeTable(subset){var rows=subset.map(function(i){return '<tr><td>'+i.quarter+'</td><td>'+i.title+'</td><td>'+i.driver+'</td><td>'+i.team+'</td><td>'+i.theme+'</td><td>'+fmtDollar(i.addedValue)+'</td><td>'+roiHtml(i.roi)+'</td></tr>';}).join('');return '<div class="twrap"><div class="thead-row">Initiatives</div><table><thead><tr><th>Quarter</th><th>Initiative</th><th>Driver</th><th>Team</th><th>Theme</th><th>Added Value</th><th>ROI</th></tr></thead><tbody>'+rows+'</tbody></table></div>';}
function roiRenderContent(q){var label=q==='all'?'All Year':q,subset=q==='all'?initiatives.filter(function(i){return i.quarter!=='Backlog';}):initiatives.filter(function(i){return i.quarter===q;});return '<div class="roi-grid">'+roiMakeOverallCard(subset,label)+roiMakeBarCard(subset,'ROI by Driver',label,'driver')+roiMakeBarCard(subset,'ROI by Theme',label,'theme')+roiMakeBarCard(subset,'ROI by Team',label,'team')+'</div>'+roiMakeTable(subset);}
function buildROISummaries(){var cq=currentQ();return buildQFilter('roi','switchROIQuarter')+'<div id="roi-content">'+buildScatterPlot(cq)+roiRenderContent(cq)+'</div>';}


function renderRoadmap() {
  var quarters=['Q1','Q2','Q3','Q4','Backlog'];
  var tableRows=initiatives.map(function(i,idx){return '<tr><td>'+i.quarter+'</td><td>'+titleCellHtml(idx)+'</td><td>'+i.driver+'</td><td>'+i.productOwner+'</td><td>'+i.techLead+'</td><td>'+i.theme+'</td><td>'+i.team+'</td><td>'+fmtDollar(i.addedValue)+'</td><td>'+roiHtml(i.roi)+'</td><td>'+dsHtml(idx)+'</td></tr>';}).join('');
  var kanban=quarters.map(function(q){var items=initiatives.filter(function(i){return i.quarter===q;});var cards=items.map(function(i){var idx=initiatives.indexOf(i),opt=deliveryOpts.filter(function(o){return o.val===i.deliveryStatus;})[0]||deliveryOpts[0],opts=deliveryOpts.map(function(o){return '<option value="'+o.val+'"'+(o.val===i.deliveryStatus?' selected':'')+'>'+o.label+'</option>';}).join('');return '<div class="kancard"><div><span class="kancard-title">'+i.title+'</span><div class="kancard-tags">'+i.theme+' \u00b7 '+i.team+'</div></div><div class="kancard-leads"><span class="kancard-lead-item"><span class="kancard-lead-label">PO</span> '+i.productOwner+'</span><span class="kancard-lead-item"><span class="kancard-lead-label">TL</span> '+i.techLead+'</span></div><div class="kancard-driver"><span class="kancard-lead-label">Driver</span> '+i.driver+'</div><div class="kancard-footer"><div class="ds-wrap" data-idx="'+idx+'"><span class="pill ds-pill '+opt.cls+'">'+opt.label+'</span><select class="ds-select" data-status-idx="'+idx+'">'+opts+'</select></div><span class="kancard-roi">'+roiHtml(i.roi)+'</span></div></div>';}).join('');return '<div class="kancol"><div class="kancol-head"><span>'+q+'</span><span class="kancol-count">'+items.length+'</span></div><div class="kancol-body">'+(cards||'<div class="empty-kanban-msg">No initiatives</div>')+'</div></div>';}).join('');
  return '<div class="roadmap-header">'
    +'<div><div class="ptitle">Product Roadmap</div><div class="psub psub-flush">Quarterly initiatives and progress status</div></div>'
    +'<a id="ob-datasource" href="https://docs.google.com/spreadsheets/d/1g7c51-WX8UqFKJzKrnPzJ_fZSKsagnNj57Jir2v9quc/edit?usp=sharing" target="_blank" class="datasource-link"><svg width="12" height="12" viewBox="0 0 16 16" fill="none"><rect x="2" y="2" width="12" height="12" rx="2" stroke="currentColor" stroke-width="1.4"/><path d="M5 5h6M5 8h6M5 11h4" stroke="currentColor" stroke-width="1.3" stroke-linecap="round"/></svg>Data source \u2192</a>'
    +'</div>'
    +'<div class="tabnav"><button class="tabitem act" data-tab="table">Table View</button><button class="tabitem" data-tab="quarterly">Quarterly</button><button class="tabitem" data-tab="roi">By ROI</button></div>'
    +'<div id="rt-table" class="tabpanel act">'+buildQFilter('tbl','switchTableQuarter')
    +'<div class="cards">'+scInitiatives()+scGrouped('sc-driver','By Driver','driver')+scGrouped('sc-theme','By Theme','theme')+scGrouped('sc-team','By Team','team')+'</div>'
    +'<div class="twrap"><div class="thead-row">Initiatives</div><div class="filter-wrap">'+buildFilterBar()+'</div>'
    +'<table><thead><tr><th>Quarter</th><th>Initiative</th><th>Driver</th><th>Product Owner</th><th>Tech Lead</th><th>Theme</th><th>Team</th><th>Added Value</th><th>ROI</th><th>Status</th></tr></thead><tbody>'+tableRows+'</tbody></table></div></div>'
    +'<div id="rt-quarterly" class="tabpanel">'+buildQuarterlyProgressBars()+'<div class="mb-16">'+buildFilterBar('q')+'</div><div class="kanban" id="kanban-wrap">'+kanban+'</div></div>'
    +'<div id="rt-roi" class="tabpanel">'+buildROISummaries()+'</div>';
}
